Repository RAD-Development/nix-dotfiles, pull requests merged in 2024-01, with the labels that each got.

#13 gitea ldap connection
  flake.lock
  systems/configuration.nix
  systems/photon/configuration.nix
  systems/photon/secrets.yaml
Labels: bug

#4 Add autopull service for testing & pre-commit-hooks
  .gitignore
  flake.lock
  flake.nix
  modules/flake-update-service.nix
  systems/configuration.nix
Labels: enhancement

#24 Adding packages
  systems/jeeves-jr/configuration.nix
  systems/programs.nix
Labels: enhancement

#26 Adding zeroteir to jeeves jr
  .gitignore
  systems/jeeves-jr/configuration.nix
Labels: enhancement

#25 creating groups for sops.yaml
  .sops.yaml
Labels: enhancement, help wanted

#39 Securing jeevesjr
  systems/configuration.nix
  systems/jeeves-jr/configuration.nix
Labels: enhancement

#40 Add pre-commit-update hook, make nixpkgs-fmt check only
  flake.nix
Labels: bug, enhancement

#44 Add ARC/FFMPEG requirements for palatine-hill
  systems/palatine-hill/configuration.nix
Labels: enhancement
