Repository RAD-Development/nix-dotfiles, pull requests merged in 2024-04, with the labels that each got.

#125 update alice's sops keys, as age key for jeeves changed
  users/alice/secrets.yaml
Labels: bug, high priority

#126 switch to nixos-unstable-small, which already finished the xz revert
  flake.lock
  flake.nix
  users/alice/systems/artemision/configuration.nix
Labels: bug, dependencies

#129 Feature/removing junk
  modules/endlessh.nix
  modules/fail2ban.nix
Labels: enhancement

#132 created nix.nix
  modules/nix.nix
  systems/configuration.nix
  users/alice/systems/artemision/non-server.nix
  users/alice/systems/non-server.nix
Labels: enhancement

#142 Feature/treefmt
  treefmt.toml
Labels: enhancement

#146 updated fail2ban module
  modules/fail2ban.nix
  systems/configuration.nix
Labels: enhancement

#145 removed programs from systems/configuration.nix and created modules/libs.nix
  modules/libs.nix
  systems/configuration.nix
Labels: enhancement

#161 does flake updates every day at noon
  .github/workflows/flake-update.yml
Labels: CI/CD

#164 Feature/gh rate limit
  users/alice/secrets.yaml
Labels: bug
