Repository RAD-Development/nix-dotfiles, pull requests merged in 2024-05, with the labels that each got.

#170 add zfs arc settings for palatine-hill
  systems/palatine-hill/configuration.nix
Labels: bug

#172 enable steam-run, gamescope
  users/alice/systems/artemision/steam.nix
Labels: enhancement

#175 Feature/onboarding davidk hydra
  users/alice/secrets.yaml
Labels: CI/CD

#176 add c++/python lsp
  users/alice/home.nix
Labels: enhancement

#185 wifi fixes
  systems/artemision/wifi.nix
Labels: bug

#190 adding steam
  .vscode/settings.json
  systems/rhapsody-in-green/configuration.nix
  systems/rhapsody-in-green/steam.nix
  users/richie/home/programs.nix
Labels: enhancement

#188 Feature/wakatime
  users/alice/home.nix
Labels: bug

#198 fix docker dir typo
  systems/jeeves-jr/docker/web.nix
Labels: bug, high priority

#201 fixes localuser warning due to plocate incompatibility
  modules/plocate.nix
Labels: bug
