Repository RAD-Development/nix-dotfiles, pull requests merged in 2024-02, with the labels that each got.

#49 enable external SMTP for hydra
  .sops.yaml
  flake.lock
  flake.nix
  modules/backup.nix
  modules/boot.nix
  modules/fail2ban.nix
  modules/flake-update-service.nix
  modules/hydra.nix
  modules/security.nix
  modules/website.nix
  systems/configuration.nix
  systems/jeeves-jr/configuration.nix
  systems/jeeves-jr/default.nix
  systems/jeeves-jr/hardware.nix
  systems/palatine-hill/configuration.nix
  systems/palatine-hill/default.nix
  systems/palatine-hill/hardware.nix
  systems/palatine-hill/secrets.yaml
  systems/photon/banner.nix
  systems/photon/configuration.nix
  systems/photon/default.nix
  systems/photon/gitea.nix
  systems/photon/hardware.nix
  systems/programs.nix
  users/alice/home.nix
  users/alice/secrets.yaml
  users/alice/systems/configuration.nix
  users/alice/systems/testtop/configuration.nix
  users/alice/systems/testtop/default.nix
  users/alice/systems/testtop/hardware.nix
  users/alice/systems/testtop/programs.nix
  users/default.nix
  users/dennis/default.nix
  users/dennis/home.nix
Labels: enhancement

#71 Disable mutable-users, fix passwords globally
  flake.lock
  flake.nix
  systems/configuration.nix
  systems/photon/configuration.nix
  systems/photon/secrets.yaml
  users/alice/secrets.yaml
  users/dennis/secrets.yaml
  users/richie/secrets.yaml
Labels: bug, enhancement

#76 Created fabius user (raspberry pi 5). Changed flake.nix.
  flake.nix
  modules/boot.nix
  systems/palatine-hill/configuration.nix
  users/dennis/systems/DennisLaptop/configuration.nix
  users/dennis/systems/DennisMain/configuration.nix
  users/dennis/systems/configuration.nix
  users/fabius/default.nix
  users/fabius/home.nix
  users/fabius/systems/RaspberryPi5/configuration.nix
  users/fabius/systems/RaspberryPi5/default.nix
  users/fabius/systems/RaspberryPi5/hardware.nix
  users/fabius/systems/RaspberryPi5/program.nix
Labels: enhancement, new user

#78 remove git-lfs from palentine-hill
  flake.lock
  systems/palatine-hill/configuration.nix
  systems/photon/configuration.nix
  systems/photon/secrets.yaml
  systems/photon/vaultwarden.nix
Labels: bug

#79 fix autopull
  flake.nix
  modules/flake-update-service.nix
  modules/website.nix
  systems/configuration.nix
  systems/palatine-hill/configuration.nix
  users/dennis/systems/DennisLaptop/configuration.nix
  users/dennis/systems/DennisMain/configuration.nix
  users/dennis/systems/configuration.nix
Labels: bug, CI/CD

#80 fix boot partition
  systems/palatine-hill/hardware.nix
Labels: bug

#83 fix mailserver config
  flake.nix
  systems/photon/configuration.nix
  users/fabius/systems/RaspberryPi5/hardware.nix
Labels: bug

#89 Fix hydra directory
  systems/palatine-hill/configuration.nix
Labels: bug

#96 Feature/server owners
  flake.nix
  systems/photon/default.nix
  users/dennis/home.nix
Labels: enhancement

#100 add override libgit2 deactivate tests
  flake.nix
Labels: bug

#103 add homemanger to dennis laptop and main
  flake.nix
  users/dennis/home.nix
  users/dennis/systems/DennisLaptop/default.nix
  users/dennis/systems/DennisMain/default.nix
  users/dennis/systems/configuration.nix
Labels: enhancement

#95 remove nix-index-database from rpi
  flake.lock
  flake.nix
  systems/palatine-hill/configuration.nix
  systems/photon/nginx.nix
  users/dennis/home.nix
  users/fabius/systems/RaspberryPi5/configuration.nix
  users/fabius/systems/RaspberryPi5/default.nix
Labels: bug

#104 some changes
  flake.lock
  flake.nix
  modules/nom.patch
  systems/configuration.nix
  systems/photon/configuration.nix
  systems/photon/gitea.nix
  systems/photon/mailserver.nix
  systems/photon/secrets.yaml
  systems/photon/vaultwarden.nix
  users/dennis/home.nix
  users/dennis/neovim.nix
  users/dennis/systems/DennisLaptop/configuration.nix
  users/dennis/systems/DennisLaptop/program.nix
  users/dennis/systems/DennisMain/configuration.nix
  users/dennis/systems/DennisMain/program.nix
  users/dennis/systems/configuration.nix
  users/dennis/systems/program.nix
Labels: enhancement
